# Generated by Django 5.2.9 on 2025-12-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0003_video_file_video_status_video_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='videos/'),
        ),
    ]
