# Generated by Django 5.2.9 on 2025-12-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0005_video_duration_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
