# Generated by Django 5.2.9 on 2025-12-15 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0010_add_unique_constraint_clip_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.FloatField(default=0)),
                ('end_time', models.FloatField(default=0)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('ratio', models.CharField(blank=True, max_length=10, null=True)),
                ('storage_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('engagement_score', models.IntegerField(blank=True, null=True)),
                ('confidence_score', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('consumption', 'Consumption'), ('refund', 'Refund'), ('purchase', 'Purchase'), ('monthly_renewal', 'Monthly Renewal'), ('adjustment', 'Adjustment')], max_length=20)),
                ('reason', models.TextField()),
                ('balance_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)')], max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('token_encrypted', models.TextField()),
                ('token_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.UUIDField()),
                ('organization_id', models.UUIDField()),
                ('video_id', models.UUIDField()),
                ('status', models.CharField(choices=[('ingestion', 'Ingestion'), ('queued', 'Queued'), ('downloading', 'Downloading'), ('normalizing', 'Normalizing'), ('transcribing', 'Transcribing'), ('analyzing', 'Analyzing'), ('embedding', 'Embedding'), ('selecting', 'Selecting'), ('reframing', 'Reframing'), ('clipping', 'Clipping'), ('captioning', 'Captioning'), ('done', 'Done'), ('failed', 'Failed')], default='ingestion', max_length=20)),
                ('current_step', models.CharField(blank=True, max_length=50, null=True)),
                ('last_successful_step', models.CharField(blank=True, max_length=50, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('configuration', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('credits_consumed', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business')], default='starter', max_length=20)),
                ('credits_monthly', models.IntegerField(default=0)),
                ('credits_available', models.IntegerField(default=0)),
                ('credits_purchased', models.IntegerField(default=0)),
                ('billing_email', models.EmailField(max_length=254)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.UUIDField()),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)')], max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('posted', 'Posted'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('post_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stripe_subscription_id', models.CharField(max_length=255, unique=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_text', models.TextField()),
                ('segments', models.JSONField(default=list)),
                ('analysis_data', models.JSONField(blank=True, default=dict, null=True)),
                ('selected_clips', models.JSONField(blank=True, default=list, null=True)),
                ('reframe_data', models.JSONField(blank=True, default=dict, null=True)),
                ('caption_files', models.JSONField(blank=True, default=list, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('confidence_score', models.IntegerField(default=0)),
                ('storage_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='videoclip',
            name='video',
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='video',
            new_name='clips_video_organiz_c13a87_idx',
            old_name='clips_video_org_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='video',
            new_name='clips_video_status_6b1b06_idx',
            old_name='clips_video_status_idx',
        ),
        migrations.RenameIndex(
            model_name='video',
            new_name='clips_video_video_i_832b2b_idx',
            old_name='clips_video_video_id_idx',
        ),
        migrations.AddField(
            model_name='clip',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='clips.video'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organization_id', '-created_at'], name='clips_job_organiz_21e349_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='clips_job_status_8fe918_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_id'], name='clips_job_job_id_d13ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user_id'], name='clips_job_user_id_d929af_idx'),
        ),
        migrations.AddField(
            model_name='clip',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='clips.job'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['organization_id'], name='clips_organ_organiz_0462b4_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['plan'], name='clips_organ_plan_5a9a13_idx'),
        ),
        migrations.AddField(
            model_name='integration',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='clips.organization'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='clips.organization'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clips.clip'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clips.organization'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='clips.video'),
        ),
        migrations.DeleteModel(
            name='VideoClip',
        ),
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['video_id', '-created_at'], name='clips_clip_video_i_70cc56_idx'),
        ),
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['clip_id'], name='clips_clip_clip_id_3c22c7_idx'),
        ),
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['engagement_score'], name='clips_clip_engagem_72ffec_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['organization_id', 'platform'], name='clips_integ_organiz_ec96c0_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['is_active'], name='clips_integ_is_acti_d046e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('organization', 'platform', 'account_name')},
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['organization_id', '-created_at'], name='clips_credi_organiz_079ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['type'], name='clips_credi_type_49d1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['user_id', '-created_at'], name='clips_sched_user_id_807519_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status'], name='clips_sched_status_7d4e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['platform'], name='clips_sched_platfor_7197ab_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization_id'], name='clips_subsc_organiz_0461d1_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='clips_subsc_status_263687_idx'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['video_id'], name='clips_trans_video_i_4c2b68_idx'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['language'], name='clips_trans_languag_6b299b_idx'),
        ),
    ]
