# Generated by Django 5.2.9 on 2025-12-15 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0011_clip_credittransaction_integration_job_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.UUIDField()),
                ('rating', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='clips.clip')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clip_id', 'user_id'], name='clips_clipf_clip_id_fb0af6_idx'), models.Index(fields=['rating'], name='clips_clipf_rating_d9becb_idx')],
                'unique_together': {('clip', 'user_id')},
            },
        ),
    ]
