# Generated by Django 5.2.9 on 2025-12-15 13:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0012_clipfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('organization_id', models.UUIDField()),
                ('type', models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('renewal', 'Renewal'), ('payment_failed', 'Payment Failed'), ('payment_succeeded', 'Payment Succeeded'), ('subscription_created', 'Subscription Created'), ('subscription_canceled', 'Subscription Canceled')], max_length=30)),
                ('old_plan', models.CharField(blank=True, max_length=20, null=True)),
                ('new_plan', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'type'], name='clips_billi_organiz_fdbb3d_idx'), models.Index(fields=['created_at'], name='clips_billi_created_d49702_idx')],
            },
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('clip_id', models.UUIDField()),
                ('format', models.CharField(default='ASS', max_length=10)),
                ('content', models.TextField()),
                ('storage_path', models.CharField(max_length=255)),
                ('style', models.CharField(choices=[('bold', 'Bold'), ('uppercase', 'Uppercase'), ('centered', 'Centered'), ('karaoke', 'Karaoke')], default='centered', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clip_id'], name='clips_capti_clip_id_111d45_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClipPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('clip_id', models.UUIDField()),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter')], max_length=20)),
                ('post_url', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['clip_id', 'platform'], name='clips_clipp_clip_id_7bdb1a_idx'), models.Index(fields=['platform', 'updated_at'], name='clips_clipp_platfor_63b4c3_idx')],
                'unique_together': {('clip_id', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('organization_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('role', models.CharField(choices=[('member', 'Member'), ('co-leader', 'Co-leader'), ('leader', 'Leader')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['organization_id', 'user_id'], name='clips_teamm_organiz_a230e5_idx'), models.Index(fields=['organization_id', 'role'], name='clips_teamm_organiz_811a8f_idx')],
                'unique_together': {('organization_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('overlay', 'Overlay'), ('bar', 'Bar'), ('effect', 'Effect'), ('text_style', 'Text Style')], max_length=20)),
                ('ffmpeg_filter', models.TextField()),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'is_active'], name='clips_templ_type_6194ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transcript_id', models.UUIDField()),
                ('text', models.TextField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('language', models.CharField(choices=[('pt-BR', 'Português (Brasil)'), ('pt-PT', 'Português (Portugal)'), ('en-US', 'Inglês (US)'), ('en-GB', 'Inglês (UK)'), ('es', 'Espanhol'), ('fr', 'Francês'), ('de', 'Alemão'), ('it', 'Italiano'), ('ja', 'Japonês'), ('zh-CN', 'Chinês (Simplificado)'), ('zh-TW', 'Chinês (Tradicional)'), ('other', 'Outro')], default='pt-BR', max_length=10)),
                ('confidence', models.IntegerField(default=100)),
                ('is_auto_detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['transcript_id', 'start_time'], name='clips_trans_transcr_a0ca78_idx'), models.Index(fields=['language'], name='clips_trans_languag_f2b06b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('organization_id', models.UUIDField()),
                ('url', models.URLField()),
                ('secret', models.CharField(max_length=255)),
                ('events', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'is_active'], name='clips_webho_organiz_63ab1f_idx')],
            },
        ),
    ]
