# Generated by Django 5.2.10 on 2026-01-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0019_organizationmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
